### ISSUE TITLE
Not the same speed on slopes

### ISSUE THREAD

**Issue by Gamepro5** [vladyslav-zaichyk/godot-first-person-player#1]
Here is the issue in action ([link](https://youtu.be/XKP7v6snOTM))

Also, I forgot to mention it but also the speed variable on the top left seems to increase on slopes.

Despite this issue, I am super grateful for the help your template has provided.

**Comment by vladyslav-zaichyk** [comment]
Speed variable was increasing because of how I calculated it. I used length of velocity vector, including y axis. That was incorrect way of calculating speed, because we need to know horizontal speed only. I made small update to the project and fixed this. Thanks!
And about slope issue: you can fix it by increasing ground friction. I've already done this in update.
